# Use a node base image
FROM node:16

# Set the working directory in the container to /app
WORKDIR /app

# Copy the frontend application source files to the container
COPY ./client ./client
COPY ./models ./models

# Change to the client directory
WORKDIR /app/client

# Install dependencies in the container
RUN npm install

# Install global serve package
RUN npm install -g serve

# Run the production script to build the app and serve it
CMD ["npm", "run", "production"]